### ISSUE TITLE
example(col2rgb) uses unavailable package xgobi

### ISSUE THREAD

**Issue by bastistician** [r-devel/bug-bbq#23] opened 2022-06-24 16:43 UTC
```
\dontrun{
 if(require(xgobi)) { ## Look at the color cube dynamically :
   tc <- t(crgb[, !duplicated(ccodes)])
   table(is.gray <- tc[,1] == tc[,2] & tc[,2] == tc[,3])  # (397, 105)
   xgobi(tc, color = c("gold", "gray")[1 + is.gray])
 }
}
```

Maybe that could be replaced by rgl::plot3d()?

Or maybe just

```r
   lattice::cloud(blue ~ red + green, data = as.data.frame(tc),
         col = c("gold", "gray")[1 + is.gray])
```

(if we wanted to stick to recommended packages.)

**Comment by hturner** [comment] 2022-06-24 16:46
This is the code I shared in Session 2

    if(require(rgl)) { ## Look at the color cube dynamically :
        tc <- t(crgb[, !duplicated(ccodes)])
        table(is.gray <- tc[,1] == tc[,2] & tc[,2] == tc[,3])  # (397, 105)
        plot3d(tc, col = c("gold", "gray")[1 + is.gray])
    }

**Comment by hturner** [comment] 2024-04-18 18:22
Duplicate of #24

**Closed as not planned by hturner** 2024-04-18 18:22 UTC
